# Site settings
title: Everest Base Camp Adventure
description: A detailed journey through our Everest Base Camp trek, including daily logs, maps, gear recommendations, and more.

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Author information (optional)
author:
  name: Theoklitos Amvrosiadis
  email: theoamvr@gmail.com

# Social media links (optional)
twitter_username: @theoamvr
github_username:  your_github
instagram_username: your_instagram

# Build settings
markdown: kramdown
theme: minima # or another theme
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed here will be excluded from site processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Plugins (uncomment to activate)
# - jekyll-feed
# - jekyll-seo-tag

# Optional: include a custom 404 page
# 404.html: your-custom-404-page.html
